### ISSUE TITLE
Portage SIHAM

### ISSUE THREAD

**Issue by jbousquie** [EsupPortail/esup-agent#6]
Bonjour,

J'ai vu qu'une version pour SIHAM était évoquée pour novembre 2016 sur cette page : https://www.esup-portail.org/wiki/pages/viewpage.action?pageId=433553414

Le portlet a-t-il finalement été porté pour SIHAM ?
Merci d'avance pour l'info.

**Comment by prigaux** [comment]
L'université Paris 1 utilise SIHAM depuis un an. Je ne peux plus maintenir esup-agent pour Harpège.

Pour SIHAM, on a choisi d'afficher directement les pages de SIHAM, avec pas mal de petites modifications, et avec la prolongationENT. Cf https://github.com/EsupPortail/ProlongationENT-apps/tree/master/siham .

**Comment by jbousquie** [comment]
Merci beacoup pour la réponse rapide.
